apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: inference-nodes
spec:
  nodePoolAutoCreation:
    enabled: false
  priorities:
  - nodepools: ['kueue-dev-a2-ultra-spt-inf']
  - nodepools: ['kueue-dev-a3-high-spt-inf']
  whenUnsatisfiable: ScaleUpAnyway
