apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: training-nodes
spec:
  nodePoolAutoCreation:
    enabled: false
  priorities:
  - nodepools: ['kueue-dev-a2-ultra-spot-trn']
  - nodepools: ['kueue-dev-a3-high-spot-trn']
  whenUnsatisfiable: ScaleUpAnyway
