# use DWS Queued provisioning to create a node that can run the training-pod template on demand
apiVersion: autoscaling.x-k8s.io/v1
kind: ProvisioningRequest
metadata:
  generateName: training-pod-
spec:
  provisioningClassName: queued-provisioning.gke.io
  parameters:
    maxRunDurationSeconds: "604800"
  podSets:
  - count: 1
    podTemplateRef:
      name: training-pod