apiVersion: v1
kind: PodTemplate
metadata:
  name: training-pod
  labels:
    cloud.google.com/apply-warden-policies: "true"
template:
  spec:
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    containers:
      - name: pi
        image: perl
        command: ["/bin/sh"]
        resources:
          limits:
            cpu: "700m"
            nvidia.com/gpu: "1"
          requests:
            cpu: "700m"
            nvidia.com/gpu: "1"
    restartPolicy: Never
