apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pubsub-argo-processor-role
  namespace: processor
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create", "get", "list", "watch"]
