apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-template
  namespace: processor
data:
  template: |
    apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      generateName: pubsub-message-
    spec:
      entrypoint: main
      templates:
        - name: main
          container:
            image: docker/whalesay
            command: [cowsay]
