apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-executor
  namespace: workflows
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
  - apiGroups:
      - autoscaling.x-k8s.io
    resources:
      - provisioningrequests
    verbs:
      - create
      - patch
      - get
      - delete