apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-a100-80gb-job
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: a100-80gb
  annotations:
    provreq.kueue.x-k8s.io/maxRunDurationSeconds: "604800" # 7 days
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      nodeSelector:
        cloud.google.com/compute-class: a100-80gb
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "cloud.google.com/compute-class"
        operator: "Equal"
        value: "a100-80gb"
        effect: "NoSchedule"
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["30s"]
        resources:
          requests:
            nvidia.com/gpu: "1"
          limits:
            nvidia.com/gpu: "1"
      restartPolicy: Never
