apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: spot
spec:
  namespaceSelector: {} # Available to all namespaces
  queueingStrategy: BestEffortFIFO # Default queueing strategy
  resourceGroups:
  - coveredResources: ["cpu", "memory", "nvidia.com/gpu"]
    flavors:
    - name: a100-80gb-spot
      resources:
      - name: "cpu"
        nominalQuota: 100           # how many total CPUs to allow for default flavor
      - name: "memory"
        nominalQuota: 800Gi         # how much total Mem to allow for default flavor
      - name: "nvidia.com/gpu"
        nominalQuota: 12            # how many total GPUs to allow for a100 gpu