apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: a100-80gb # This ResourceFlavor for A100 80GB nodes
spec:
  nodeLabels:
    cloud.google.com/compute-class: a100-80gb
  nodeTaints:                # node taints that this resource flavor represents
  - effect: NoSchedule
    key: cloud.google.com/compute-class
    value: "a100-80gb"
  - key: "nvidia.com/gpu"
    value: "present"
    effect: "NoSchedule"
  tolerations:               # tolerations added to pods -- admit to the node taints above
  - key: "cloud.google.com/compute-class"
    operator: "Equal"
    value: "a100-80gb"
    effect: "NoSchedule"